#!/usr/bin/env python
"""Regenerate reviewed SETA briefing payloads with Card Jobs V2 copy.

This script reads the current generated_briefings_reviewed.json, regenerates each
existing reviewed briefing key using the deterministic local generator, validates
each output, and writes the reviewed payload back to disk.

It preserves the current reviewed key matrix. It does not add new assets or
ranges by default.
"""

from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from build_ai_briefing_input import build_input
from check_ai_briefing_output import validate_output
from generate_ai_briefing_draft import generate_draft

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_PATH = ROOT / "generated_briefings_reviewed.json"


def read_json(path: Path) -> dict[str, Any]:
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError(f"{path} root must be a JSON object")
    return data


def key_for(mode: str, asset: str, frequency: str, display_range: str, as_of: str) -> str:
    date_token = str(as_of).replace("-", "_")
    return f"{mode.lower()}::{asset.lower()}::{frequency.lower()}::{display_range.lower()}::{date_token}"


def reviewed_metadata(now_utc: str, source_key: str) -> dict[str, Any]:
    return {
        "reviewer": "local-deterministic-card-jobs-v2",
        "reviewed_at_utc": now_utc,
        "review_note": (
            "Regenerated with Card Jobs V2 deterministic template; inspected through local "
            "schema, semantic regression, and dashboard smoke validation workflow."
        ),
        "source_draft_path": "generated by scripts/regenerate_reviewed_briefings_v2.py",
        "source_input_schema_version": "ai_briefing_input_v1",
        "source_payload_key": source_key,
    }


def regenerate_one(existing_key: str, existing: dict[str, Any], now_utc: str, *, keep_existing_keys: bool) -> tuple[str, dict[str, Any], list[str]]:
    mode = str(existing.get("mode") or "public").lower()
    asset = str(existing.get("asset") or "").upper()
    frequency = str(existing.get("frequency") or "D").upper()
    display_range = str(existing.get("display_range") or "3M").upper()

    if not asset:
        raise ValueError(f"{existing_key}: missing asset")

    briefing_input = build_input(mode, asset, frequency, display_range)
    draft = generate_draft(briefing_input)
    errors = validate_output(draft, briefing_input)
    if errors:
        return existing_key, draft, [f"{existing_key}: {error}" for error in errors]

    output_key = existing_key if keep_existing_keys else key_for(mode, asset, frequency, display_range, draft["as_of"])

    draft["mode"] = mode
    draft["display_range"] = display_range
    draft["payload_key"] = output_key
    draft["review_status"] = "reviewed"
    draft["review_metadata"] = reviewed_metadata(now_utc, existing_key)

    return output_key, draft, []


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--path", default=str(DEFAULT_PATH), help="Reviewed payload JSON path.")
    parser.add_argument("--output", help="Optional output path. Defaults to overwriting --path.")
    parser.add_argument(
        "--refresh-keys",
        action="store_true",
        help="Use generated as_of date in payload keys. Default preserves existing keys for dashboard lookup stability.",
    )
    parser.add_argument("--dry-run", action="store_true")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    path = Path(args.path)
    out_path = Path(args.output) if args.output else path
    payload = read_json(path)

    briefings = payload.get("briefings")
    if not isinstance(briefings, dict) or not briefings:
        raise ValueError(f"{path} must contain a non-empty 'briefings' object")

    now_utc = datetime.now(timezone.utc).replace(microsecond=0).isoformat()
    regenerated: dict[str, Any] = {}
    all_errors: list[str] = []

    for existing_key, existing in sorted(briefings.items()):
        if not isinstance(existing, dict):
            all_errors.append(f"{existing_key}: briefing value must be an object")
            continue
        output_key, draft, errors = regenerate_one(
            existing_key,
            existing,
            now_utc,
            keep_existing_keys=not args.refresh_keys,
        )
        all_errors.extend(errors)
        regenerated[output_key] = draft

    if all_errors:
        for error in all_errors:
            print(f"[ERROR] {error}")
        return 1

    next_payload = dict(payload)
    next_payload["briefing_count"] = len(regenerated)
    next_payload["briefings"] = dict(sorted(regenerated.items()))
    next_payload["reviewed_payload_generated_at_utc"] = now_utc
    next_payload["reviewed_payload_generator"] = "scripts/regenerate_reviewed_briefings_v2.py"
    next_payload["reviewed_payload_contract"] = "briefing_card_jobs_v2"

    if args.dry_run:
        print(f"[OK] dry run regenerated {len(regenerated)} reviewed briefing(s)")
        for key in list(sorted(regenerated))[:5]:
            item = regenerated[key]
            print(f"  - {key}: {item.get('headline')}")
        return 0

    out_path.write_text(json.dumps(next_payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"[OK] wrote {out_path} with {len(regenerated)} reviewed briefing(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
